#pragma once

// clang-format off
// generated by /home/igor/NVMe-Linux/Projects/alive-fobs/src/db_schemas/sqlpp23-ddl2cpp --path-to-ddl /home/igor/NVMe-Linux/Projects/alive-fobs/src/db_schemas/motherbase_data.sql --path-to-header /home/igor/NVMe-Linux/Projects/alive-fobs/src/db_schemas/motherbase_data.hpp --namespace table --generate-table-creation-helper

#include <optional>

#include <sqlpp23/core/basic/table.h>
#include <sqlpp23/core/basic/table_columns.h>
#include <sqlpp23/core/name/create_name_tag.h>
#include <sqlpp23/core/type_traits.h>

namespace table {
  template<typename Db>
  void createMotherbases(Db& db) {
    db(R"+++(CREATE TABLE IF NOT EXISTS motherbases (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    motherbase_id INTEGER UNSIGNED UNIQUE,
    owner_player_id INTEGER UNSIGNED,
    area_id INTEGER UNSIGNED,
    construct_param INTEGER UNSIGNED,
    platform_count INTEGER UNSIGNED,
    security_rank INTEGER UNSIGNED
))+++");
  }

  struct Motherbases_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::true_type;
    };
    struct MotherbaseId {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(motherbase_id, motherbaseId);
      using data_type = std::optional<::sqlpp::unsigned_integral>;
      using has_default = std::true_type;
    };
    struct OwnerPlayerId {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(owner_player_id, ownerPlayerId);
      using data_type = std::optional<::sqlpp::unsigned_integral>;
      using has_default = std::true_type;
    };
    struct AreaId {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(area_id, areaId);
      using data_type = std::optional<::sqlpp::unsigned_integral>;
      using has_default = std::true_type;
    };
    struct ConstructParam {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(construct_param, constructParam);
      using data_type = std::optional<::sqlpp::unsigned_integral>;
      using has_default = std::true_type;
    };
    struct PlatformCount {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(platform_count, platformCount);
      using data_type = std::optional<::sqlpp::unsigned_integral>;
      using has_default = std::true_type;
    };
    struct SecurityRank {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(security_rank, securityRank);
      using data_type = std::optional<::sqlpp::unsigned_integral>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(motherbases, motherbases);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               MotherbaseId,
               OwnerPlayerId,
               AreaId,
               ConstructParam,
               PlatformCount,
               SecurityRank>;
    using _required_insert_columns = sqlpp::detail::type_set<>;
  };
  using Motherbases = ::sqlpp::table_t<Motherbases_>;

} // namespace table
