CREATE TABLE IF NOT EXISTS rankings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    player_id INTEGER UNSIGNED UNIQUE,
    fob_grade INTEGER UNSIGNED,
    fob_point INTEGER UNSIGNED,
    fob_rank INTEGER UNSIGNED
)