#pragma once

// clang-format off
// generated by /home/igor/NVMe-Linux/Projects/alive-fobs/src/db_schemas/sqlpp23-ddl2cpp --path-to-ddl /home/igor/NVMe-Linux/Projects/alive-fobs/src/db_schemas/player_data.sql --path-to-header /home/igor/NVMe-Linux/Projects/alive-fobs/src/db_schemas/player_data.hpp --namespace table --generate-table-creation-helper

#include <optional>

#include <sqlpp23/core/basic/table.h>
#include <sqlpp23/core/basic/table_columns.h>
#include <sqlpp23/core/name/create_name_tag.h>
#include <sqlpp23/core/type_traits.h>

namespace table {
  template<typename Db>
  void createPlayers(Db& db) {
    db(R"+++(CREATE TABLE IF NOT EXISTS players (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    player_id INTEGER UNSIGNED UNIQUE,
    xuid BIGINT UNSIGNED,
    last_time_online DATETIME
))+++");
  }

  struct Players_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::true_type;
    };
    struct PlayerId {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(player_id, playerId);
      using data_type = std::optional<::sqlpp::unsigned_integral>;
      using has_default = std::true_type;
    };
    struct Xuid {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(xuid, xuid);
      using data_type = std::optional<::sqlpp::unsigned_integral>;
      using has_default = std::true_type;
    };
    struct LastTimeOnline {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(last_time_online, lastTimeOnline);
      using data_type = std::optional<::sqlpp::timestamp>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(players, players);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               PlayerId,
               Xuid,
               LastTimeOnline>;
    using _required_insert_columns = sqlpp::detail::type_set<>;
  };
  using Players = ::sqlpp::table_t<Players_>;

} // namespace table
