#pragma once

// clang-format off
// generated by /home/igor/NVMe-Linux/Projects/alive-fobs/src/db_schemas/sqlpp23-ddl2cpp --path-to-ddl /home/igor/NVMe-Linux/Projects/alive-fobs/src/db_schemas/player_ranking_data.sql --path-to-header /home/igor/NVMe-Linux/Projects/alive-fobs/src/db_schemas/player_ranking_data.hpp --namespace table --generate-table-creation-helper

#include <optional>

#include <sqlpp23/core/basic/table.h>
#include <sqlpp23/core/basic/table_columns.h>
#include <sqlpp23/core/name/create_name_tag.h>
#include <sqlpp23/core/type_traits.h>

namespace table {
  template<typename Db>
  void createRankings(Db& db) {
    db(R"+++(CREATE TABLE IF NOT EXISTS rankings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    player_id INTEGER UNSIGNED UNIQUE,
    fob_grade INTEGER UNSIGNED,
    fob_point INTEGER UNSIGNED,
    fob_rank INTEGER UNSIGNED
))+++");
  }

  struct Rankings_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::true_type;
    };
    struct PlayerId {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(player_id, playerId);
      using data_type = std::optional<::sqlpp::unsigned_integral>;
      using has_default = std::true_type;
    };
    struct FobGrade {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(fob_grade, fobGrade);
      using data_type = std::optional<::sqlpp::unsigned_integral>;
      using has_default = std::true_type;
    };
    struct FobPoint {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(fob_point, fobPoint);
      using data_type = std::optional<::sqlpp::unsigned_integral>;
      using has_default = std::true_type;
    };
    struct FobRank {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(fob_rank, fobRank);
      using data_type = std::optional<::sqlpp::unsigned_integral>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(rankings, rankings);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               PlayerId,
               FobGrade,
               FobPoint,
               FobRank>;
    using _required_insert_columns = sqlpp::detail::type_set<>;
  };
  using Rankings = ::sqlpp::table_t<Rankings_>;

} // namespace table
